# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @return a random sample (x,y)
#' @examples
#' \dontrun{
#' GibbsC(100)
#' }
#' @export
GibbsC <- function(N) {
    .Call('_StatComp21024_GibbsC', PACKAGE = 'StatComp21024', N)
}

